name: 'CI: National Delivery Fulfilment'
on: [push]
jobs:
  ci:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.11.0
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: |
          pnpm install
          pnpm lint
          pnpm type-check
          pnpm test-coverage
          pnpm build
          pnpm package
      - name: CDK synth
        run: |
          pnpm install
          pnpm tsc
          pnpm lint
          pnpm test
          pnpm synth
        working-directory: cdk
      - name: AWS Auth
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1
      - name: Upload to riff-raff
        uses: guardian/actions-riff-raff@v4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          configPath: riff-raff.yaml
          projectName: MemSub::Fulfilment::NationalDelivery
          buildNumberOffset: 60
          contentDirectories: |
            cdk.out:
              - cdk/cdk.out/NationalDeliveryFulfilment-CODE.template.json
              - cdk/cdk.out/NationalDeliveryFulfilment-PROD.template.json
            national-delivery-fulfilment:
              - cdk/national-delivery-fulfilment/national-delivery-fulfilment.zip
